os: linux
dist: xenial
language: python

jobs:
  include:
    - python: '3.6'
    - python: '3.7.3'
    - python: '3.8.2'

install:
  - pip install -r requirements.txt

script:
  - scrapy runspider games.py -o gm.jl -a items_per_page=15 -s CLOSESPIDER_PAGECOUNT=1
  - scrapy runspider analyze.py
